[package]
name = "bls381_new"
version = "0.1.0"
authors = ["nalos"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paired = "0.15.1"
rand = "0.4"
xorshift = "0.1.1"
lazy_static = "1.4.0"
